var states = ['ARK SURVIVAL','BadNoath','BeatSaber',"Don't Starve TogeTier",'The Forest','Amazing Frog?','Gang Beasts','Human fall flat'
,'ISAAC','Hollow Knight','The Last Hope','ICONDCL STS','RAFT',"Rimworld",'RUST','Slay the Spire','Thief Simulator','UNDERTALE'
,'Stardew Valley','Nigth in the Woods','Car Mechanic Simulator 2018','MIST SURVIVAL','Universe Sandbox2',"The Witch's House",'The Messengep','Two Point Hospital','ARIZONA SUNSWINE','The Long Dark'
,'Ammesia','Oriental Empires DLC','Plague Inc Evolved','My Time Portla','HOUSE FLIPPER','Just shapes & beats','KINGDDOM RUSH','The Room Three','Sins of a Solar Empire','Enter The Gungeon','To The Moon','Oriental Empires','Ahatin Time','Facerig','Battle Brothers',"Don't Starve",'World War3','Call To Arms','Rising storm 2 vietnam','OXYGEN NOT INCLUDED SPACE','The Vaggant','AnGvik','Project Hospital','Luna Nights','Little Nightmares','Last Tide','60 SECONDS!','Euro Truck Simulator2','Dead Ground Arena','ASTRONEER','Assault 594','Poly Bridge','neShot','INSIDE','HOT DOGS'
,'Warriors','Tabletop simulator','Celeste','Trouble Shooter','Finding Raradise','CupHead','One Hour One Life','Bendy','Green Hell','Obra Dinn','We Were Here','HoldFast','SimAirport','Rain World','Racket NX','MOONLIGHTER','The BlackoutClub','Cultist Simulator','Gold Rush','BadeLine','Monstrum','RIFT','Wizard of Legend','STARD UND','Vector36','Project Zombie','TheAter','Yet Another Zombie Defense Hd','Ravenfield','Oceanhorn'
,'Mad Tower Tycoon','Drakwood','Niffelheim','Hacknet','This Is The Police','The Stanley Parable','Move or Die'
,'DOOR','Donut County','Rock of Ages','Simple Rockets2','Life is Starange','Mini Metro','Nino Kuni'
,'BARRLEGROUNDS','RAINBOWSIX','Grand Theft Auto','Dead by daylight','Monster Hunter','ARK SURIVAL','TOTAL WAR'
,'Assassins creed','The Foreest','HITMAN2','Puyopuyo','Thief Simulator','SKYRIM','THREE KINGDOMS'
,'The WALKINGDEAD','The witcher','DUNGREED','COUNTER STRIKE','Fallout4','COMPANY of HEROES2','Left4Dead2'
,'Tomb Raider','Battletech','Conan exiles','Dead Space','Feed and Grow','Deserts of kharak','Resident evil2'
,'VALKYRIA4','PAYDAY2','JUST CAUSE 4','FARCRY 2','DARK SOULS3','kingoom Come','SNIPER ELITE4'
,'TAPSONIC BOLD','Deuil maucry5','SEKIRO','INSURGENCY','OSM','DRAGONBALL2','Sunset Overdrive'
,'Mount & Blade','Crazy Fishing','Crstle Crasher5','RAINBOWSIX VEGAS','Dying Light','Project Cars2','Megaman11'
,'king of fighters xiii steam edition','Getting Over It','Owlboy','Zero Caliber','WRECKFFST','Super Bunny Man','XCOM'
,'Terraria','Steep','Killing Floor2','Out Last','Watch Dogs','SuperHot','Overcooked2'
,'Sniper3','HellGate','SCUM','Life is Starange DLC','DOOM','Deeper','Killer7'
,'Titan Quest','GROOVE COASTER','Super Luckys Tale',"Mirror's Edge",'Red Alert3','Murderousl Pursults','NARUTO STORM3'
,'VERMINTIDE','OSIRIS','Kepp Talking','Thekingof Fighters','Crypt of the Necro Dancer','Construction Simulator','Streers of Rogue'
,'Serlal Cleaner','Stick Fight','Haycee','UEBS','Paint The Town Red','From The Depths','among the sleep'
,'ARENA','GUNS,GORE & CANNOLI2','ELVEN ASSASSIN','Assassins Creed2','Geometry Dash','One Gun: Cat','Kingdoms and Castles'
,'niohogg','Bouncing Over It','Elmia','Metal Slug X','Hero Siege','Rules of Survival','Apollo 11'
,'Super Jet Juck','Beat Stickman','Secret of the Rendrayha Blade','The Haunted Island','Elon Musk Simulator2','The ExperIment','Shakes & Fidget'
,'Grooming Adventure','Neon.Code','The Choice Of Sand','Absinth','Granny','Stanm Boy','Rogue Rails'
,'The Kite','Doctor Tsunami','Tango','Double','Indiana Jones','Hit the Road','Monkey Island'
,'Zak Mckracken','Sub Nautica','Bayoneia','The Wild Eight','Border lands','Bio Shock Infinite','Dount County'
,'Divinity','Darksiders3','Wuppo','Portla','Half Life','Pixark','American Truck'
,'For The King',"Death's Gambit",'Full Metal Furies','Shining Resonance','The Line','7 Days To Die','The Old Blood'
,'Slime Rancher','Crimes & Punishments',"Balaur's Gate2",'Spelunky','Armello','Cave Story','Black Mesa'
,'Tower Unite','ys seven','LIMBO','Wonder Boy','Colony Suruiual','60 PARRSECS!','Sunset Verorme'
,'Pathfinder','Final Fantasy 13','ETERNTY WARRIORS',"Dragon's Dogma",'ABZU','MOMODORA',"GOD'S BASEMENT",'bio Shock REMASTERE','FIRE WATCH','RIME','SONIC FORCES'
,'resident evil 4','We Were Here Too','Rusty Lake Paradise','The Red Strings Club','DIS Honored','L.A. NOIRE','ibb obb','Be holder','Deserts of kharak','Lightning Returns','RAKUEN'
,'PREV','AIR TONE','MOSS','Spore','Hand Of Fate','Titan Souls','Mass Effect2','YOMAWARI','A bird Story','DREAMFALL CHAPTERS','SHADOW WARRIOR'
,'Dawn of War','Taransference','The Isle','Devil May Cry','minit game','Cat Quest','The TALOS','Hell Neighbor','Lovers','The Coma','FEZ'
,'sword legacy omen','RWBY','Macicka2','VIKING'
,'Tekken7','PES2019','NBA2K19','Assetto Corsa','The Hunter','F1 2018','Dirt Rally','Super Mega Baseball2','Eleven Table Tennis','Wreckfest','First Person Tennis','Ultimate Fishing','rFactor 2'
,'Super Sports Challenge','Golf With Your Friends','Racket Fury','Golf it','Frult Ninja','GRID AUTOSPORT','PUNCH CLUB','SpeedRunner','MotoRSPORT Manager','iRacing','Pyre','Worms Reloaded','Super fLight'
,'Car Drift Racing Online','Star Drift','Super Blood Hockey','Paradise','CHESS ULTRA','STIK BOLD','Final Soccer','Dare Course','FOOTLOL','Wild Animal Racing','Eleven Table Tennis','Gun Club VR','RUSH'
,'VR GOLF ONLINE','YOUTUBER PACK 1','SAM & MAX','the games','SPRINT VECTOR','WSC 7','Assetto Corsa COMPETIZIONE','Tennis Elbow 2013','AO INTERNATIONAL','FRANCHISE HOCKEY MANAGER','Tennis World Tour','MotoGP18','Final Soccer DLC'
,'NBA2K PLAYGROUNPS2','DESCENDERS','Pro Cycling Manager','RUN DANT RUN','Summer Funland','Social Club VR','Wild Animal Sports Day','Death Stair','Go Kart Racing','Deadly Wheels','Ride2','Tennis Elbow 2013 DLC','Sports BAR VR'
,'ultra space battle brawl ','ESPORTS LEGEND','Nippon Marathon','AIM TRAINER PRO','EXTREME','River City Melee','DISC JAM','Mad snowboarding','Rebons','DASH DASH RUN','MAHJONG','TEDDY FLOPPY EAR','JUST GET THROUCH'
,'Carfield Kart','ARENA','THROTTLE POWAH','NO SEAT','Aiball','VerChunked','Blonde Driver','Achievements printer','Contact Draw Bowling','DARTS AND FRIENDS','SIMPLE SALING','POOPY PHILOSOPHY','Super Darts'
,'Kubble','Owl Watch','Bunny Mahjo','Centifeed','CEFORE',"Ocean's Treasures",'Enemist','Grid Defense','GameEllen','ONE MORE ROLL','RUYA','SAVE THE COOKIE','Suitchi'
,'FAT CITY'
];